spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.banking: DEBUG
    org.springframework.security: DEBUG

